### ISSUE TITLE
Clicking on the thumbnail strip to change images does not update the description

### ISSUE THREAD

**Issue by spacenate** [SchwarzwaldFalke/ngGallery#14]
First off, thanks for creating this gallery module!

I noticed a small issue when changing images, while viewing a gallery. If you click on a thumbnail in the thumbnail strip, instead of using the left or right arrows, the description does not get updated.

It seems this is due to `changeImage()` calling `loadImage()` directly, instead of `showImage()` (like `nextImage()` and `prevImage()` do).

**Comment by SchwarzwaldFalke** [comment]
Should be fixed.
