### ISSUE TITLE
Possible to open ngGallery on page load?

### ISSUE THREAD

**Issue by mebekah** [SchwarzwaldFalke/ngGallery#18]
I'm new to angular, so apologies if this is a silly question. What is the best way to call openGallery(); on page load? My attempts to do this so far have returned "openGallery is not defined" as I believe I am out of scope.

Thanks in advance for any guidance you can offer! And thanks for the slideshow, it's great!

**Comment by jkuri** [comment]
That option is currently not available, the best option for you is to fork the repository and customize it for you needs. If you need any further help please let me know.

**Comment by notVitaliy** [comment]
@mebekah In case you still need it, I forked the repo (and submitted a PR here) and made it so that it will allow you to open on page load:

https://github.com/visikov/ngGallery/tree/master

You just need to do something like this in your parent controller:

```
    $scope.openGallery = function(index) {
        $scope.$broadcast("openGallery", {index: index});
    };
    $scope.openGallery(0);
```
