### ISSUE TITLE
After openGallery doesn't show image

### ISSUE THREAD

**Issue by PALLY27** [SchwarzwaldFalke/ngGallery#19]
Gallery after open doesn't show image in screen. Thumbnails are showing, but  in main screen is still showing loading ring.

I think that is problem with "showImage" function, but I was check image paths and looks right. 
![nggallery problem](https://cloud.githubusercontent.com/assets/16815519/12476456/b0f262d8-c029-11e5-9bdf-3f6a5366302c.png)

**Comment by jkuri** [comment]
What does javascript console log says?

**Comment by PALLY27** [comment]
I put debugger to showImage function. after execute of showImage(), scope.img is "undefined" .. .. so response from loadImage func. is maybee bad.  And in load image  image.src is right

**Comment by jkuri** [comment]
Hm, interesting, nobody so far complained about that... are you 100% sure that `img` path is right... it might be that path to `thumb` is right but path to `img` is not. If the issue still persist please let me know and we will solve this.

**Comment by PALLY27** [comment]
OK Problem solved.
Problem is in showImage function. There is loadImage function, but method "then" doesn't run. It makes problem that scope.img is undefined.

So I make workaround/hack  in loadImage function and I assign directly in this function 
scope.img = image.src
and maked substring of location protocol and host,  because I need relative path of image (cause deferred.resolve(image) is here)

after substring I assign back image.src = scope.img

Now is image showing, but sometimes Thumbs width doesn't work good. (I didn't debug this)
![nggallery problem2](https://cloud.githubusercontent.com/assets/16815519/12478188/cbd74488-c033-11e5-8d48-fd715ee82250.png)

**Comment by jkuri** [comment]
Ok, cool.
