### ISSUE TITLE
Mispelled app.js code

### ISSUE THREAD

**Issue by matapatos** [SchwarzwaldFalke/ngGallery#24]
In the example that you give for the 'app.js' it's written 'self.images' and it should be 'this.images'.

And well done for the gallery! ;)

**Comment by SchwarzwaldFalke** [comment]
Hi,

you talk about this code snippet?

```
myApp.controller('Ctrl', [function() {
    var self = this;
    self.images = [
        {thumb: 'images/thumbs/1.jpg', img: 'images/1.jpg', description: 'Image 1'},
        {thumb: 'images/thumbs/2.jpg', img: 'images/2.jpg', description: 'Image 2'},
        {thumb: 'images/thumbs/3.jpg', img: 'images/3.jpg', description: 'Image 3'},
        {thumb: 'images/thumbs/3.jpg', img: 'images/4.jpg', description: 'Image 4'}
    ];
]);
```

**Comment by matapatos** [comment]
Hey dude,

similar one.

In here:

[cid:9c3a39b0-003b-41ba-b579-0bb7349ce4b9]

**Comment by matapatos** [comment]
If you notice in the print screen, you can see that you just miss to declare self. And that's it.

var self = this;

**Comment by SchwarzwaldFalke** [comment]
Hi Manuel,

sorry, I can't see any print screen.
Can you please just link to the code or copy/paste it here? I'm still not sure which example you talk about. :/
