### ISSUE TITLE
How to set downloadSrc?

### ISSUE THREAD

**Issue by MaccerC** [SchwarzwaldFalke/ngGallery#29]
I cannot find out how to make the download button to show. I read something about downloadSrc property, but how do I set this property?

**Comment by SchwarzwaldFalke** [comment]
Hi MaccerC,

heres an pretty basic example:
https://github.com/SchwarzwaldFalke/ngGallery/tree/examples/examples

The downloadSrc property is set inside your angular [app.js](https://github.com/SchwarzwaldFalke/ngGallery/blob/examples/examples/basic/js/app.js).

If you still have problems please post some more details. 

Cheers,
Chris
