### ISSUE TITLE
scrollLeft error

### ISSUE THREAD

**Issue by satore11** [SchwarzwaldFalke/ngGallery#30]
Hi,
i get this error: Cannot read property 'scrollLeft' of undefined (ngGallery.js:207)

``` javascript
...
current_scroll = $thumbwrapper[0].scrollLeft,
...
```

I've update the library at the latest version, with the merge for allow the multiple galleries in one page.
What can i do for fix this?
Thanks a lot!

**Comment by SchwarzwaldFalke** [comment]
Hi,
can you please upload an example?

**Comment by MaccerC** [comment]
i have the same error when viewing a single image.
This is my js code:
var app = angular.module('galley', ['jkuri.gallery']);

app.controller('Ctrl', ['$scope', '$document', function($scope, $document){

	$scope.images = [
		  {"thumb": "images/thumbs/piraten-01.jpg", "img": "images/views/piraten-01.jpg", "downloadSrc": "images/downloads/piraten-01.jpg"},
          {"thumb": "images/thumbs/piraten-02.jpg", "img": "images/views/piraten-02.jpg", "downloadSrc": "images/downloads/piraten-02.jpg"},
          {"thumb": "images/thumbs/piraten-03.jpg", "img": "images/views/piraten-03.jpg", "downloadSrc": "images/downloads/piraten-03.jpg"},
          {"thumb": "images/thumbs/piraten-04.jpg", "img": "images/views/piraten-04.jpg", "downloadSrc": "images/downloads/piraten-04.jpg"}
         ];

}]);


And this is my html code:
....
<div class="content">
     <ng-gallery images="images" thumbs-num="7"></ng-gallery>
</div>
......

Also: attribute 'thumbs-num' is not working either.

**Comment by MaccerC** [comment]
I have the very same error.
This is my JS code:

`var app = angular.module('galley', ['jkuri.gallery']);

app.controller('Ctrl', ['$scope', '$document', function($scope, $document){

```
$scope.images = [
      {"thumb": "images/thumbs/piraten-01.jpg", "img": "images/views/piraten-01.jpg", "downloadSrc": "images/downloads/piraten-01.jpg"},
      {"thumb": "images/thumbs/piraten-02.jpg", "img": "images/views/piraten-02.jpg", "downloadSrc": "images/downloads/piraten-02.jpg"},
      {"thumb": "images/thumbs/piraten-03.jpg", "img": "images/views/piraten-03.jpg", "downloadSrc": "images/downloads/piraten-03.jpg"},
      {"thumb": "images/thumbs/piraten-04.jpg", "img": "images/views/piraten-04.jpg", "downloadSrc": "images/downloads/piraten-04.jpg"}
     ];
```

}]);`

And here is the HTML code:
`<!DOCTYPE html>
<html lang="en" ng-app="galley">
    <head>
        <title>Gallery</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
        <link href="css/ngGallery.css" media="all" rel="stylesheet" type="text/css" />
        <link href="css/screen.css" media="all" rel="stylesheet" type="text/css" />

```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.2/angular.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.2.min.js" integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="js/ngGallery.js"></script>
    <script src="js/app.js"></script>

</head>

<body ng-controller="Ctrl">

<div class="container">
    <div class="content">
        <ng-gallery images="images" thumbs-num="7"></ng-gallery>
    </div>
</div>
</body>
```

</html>`

I hope you can sort this out for me.
Grtz,
MaccerC

**Comment by satore11** [comment]
My code is the documentation example that after update not work for me, I have not yet adapted to my needs.
Simple gallery with 11 thumbs and images.
You will not have the same mistake?
Thankyou and sorry for my bad english
Satore
