### ISSUE TITLE
No close button, downloadbutton and navigation arrows

### ISSUE THREAD

**Issue by MaccerC** [SchwarzwaldFalke/ngGallery#32]
I'm getting these errors in the console:

Error: undefined is not an object (evaluating 'scope.index')
getImageDownloadSrc@http://xxx.xxx.xxx.xxx/Galley/js/ngGallery.js:128:43

Error: undefined is not an object (evaluating 'scope.index')
showImageDownloadButton@http://xxx.xxx.xxx.xxx/Galley/js/ngGallery.js:122:43

When I click an image there is no downloadbutton, nor close-button, and there are also no left and right arrows.

This is my JS code:

`var app = angular.module('galley', ['jkuri.gallery']);

app.controller('Ctrl', ['$scope', '$http', '$document', function($scope, $http, $document){

```
$http.get('images.json').success(function(data){
    $scope.images = data;
})
```

}]);`

How to fix this? Is my code wrong?

Gtrz,
MaccerC

**Comment by SchwarzwaldFalke** [comment]
Hi!
Could you please post an complete example including the html file?
What does "data" contain? If it's JSON you should probably parse it first and then assign it to $scope.images.

**Comment by MaccerC** [comment]
I've made a plunk. You can find it here: https://plnkr.co/edit/5hRnS8vNmr88t9DWOuis

Unfortunately I was not able to get the images in this plunk. I have them locally.
'Data' is the response from $http.get. 
I renamed data to 'resp' as you can see in my code.
It's indeed JSON. But I think it's a proper JSON file and I am not sure if I should parse it first before assigning it to $scope.images.

**Comment by SchwarzwaldFalke** [comment]
If I open your plunkr example I get multiple errors:
`
ReferenceError: System is not defined
 angular2.min.js:1:19
ReferenceError: angular is not defined
 ngGallery.js:4:5
ReferenceError: angular is not defined
`
Also I'm not sure if ngGallery works with AngularJS 2 (which is used in your example).

It would be really nice if you could upload a complete example (maybe without the Ajax request, just hardcode the $scope.images in your controller).

**Comment by MaccerC** [comment]
I'm very sorry I didn't check the Angular version. I didn't mean to use Angular 2.
Now I've changed it in my Plnkr: https://plnkr.co/edit/5hRnS8vNmr88t9DWOuis?p=preview

However, I don't know how to give you a complete example. I hardcoded the $scope.images in which I put the url where the images are stored. But they don't show up so I can't show the problem where it's all about.

**Comment by SchwarzwaldFalke** [comment]
Hi MaccerC,

I tried to fix your plunkr:
- Add ngGallery.css
- Added ng-app and ng-controller in index.html
- Added Font-Awesome
- Fixed typo in your ng-app name

Now it seems to work:
https://plnkr.co/edit/MZ5NWlmhY7rqOxvXSuJv?p=info

Cheers,
Chris

**Comment by MaccerC** [comment]
Great! Now it works like a charm. I'm very sorry for my own mistakes and typo's....
