### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by a-shku** [SchwarzwaldFalke/ngGallery#33]
Hi! I have done all by instruction but have errors http://joxi.ru/KAgZN9BFgbz1x2
What could be the problem?

**Comment by SchwarzwaldFalke** [comment]
Hi!
How did you solve it?

**Comment by a-shku** [comment]
I don't know why but errors disappeared. I tried use ngGallery-buras and then turned to ngGallery back again and it worked. But it working via scope.
