### ISSUE TITLE
Page scrolling in background

### ISSUE THREAD

**Issue by aaxc** [SchwarzwaldFalke/ngGallery#34]
On opened gallery, there should be an option to remove page scrolling. Meaning, a parameter, to set _body{overflow:hidden;}_ on open and remove it on gallery close.

I apologize, if there already is such option.

**Comment by thatisuday** [comment]
@aaxc There is a fix. Go to ngGallery.js and
1. Add `document.body.style.overflow = 'hidden';` below `scope.opened = true;` line inside `scope.openGallery` function
2. Add `document.body.style.overflow = '';` below `scope.opened = false;` line inside `scope.closeGallery` function

**Comment by SchwarzwaldFalke** [comment]
I'm not sure if we should add this to ngGallery.
Changing styles of body sounds kind of dangerous to me.
@jkuri What do you think?

**Comment by aaxc** [comment]
@thatisuday Thank you, I didn't ask for a fix, I already added `$('body').css({overflow: 'hidden'});` and `$('body').css({overflow: 'auto'});` before those lines. I just thought this should also have a parameter like **hide-overflow="true"** similar to  **thumbs-num="3"**.

@SchwarzwaldFalke And I don't think that it's dangerous, since even bootstrap has this option enabled for their modals by default.

PS: Really nice script, is perfect for my project!
