### ISSUE TITLE
TypeError: Cannot read property 'img' of undefined

### ISSUE THREAD

**Issue by thatisuday** [SchwarzwaldFalke/ngGallery#35]
This error occurs while clicking on previous button when preview is on first image on list.

**Comment by thatisuday** [comment]
Fix is here
_```
scope.prevImage = function () {
	scope.index -= 1;
	if (scope.index < 0) {
		scope.index = scope.images.length;
		scope.prevImage();
		return;
	}
	showImage(scope.index);
};
```_

**Comment by thatisuday** [comment]
I guess because you set index to images length _scope.index = scope.images.length_ in **scope.prevImage** function. Actually, it should be set to _scope.images.length - 1_ as we are dealing images from index=0 and not index = 1

**Comment by SchwarzwaldFalke** [comment]
About which version do you talk?
In master scope.prevImage is the following code:

```
scope.prevImage = function () {
                    scope.index -= 1;
                    if (scope.index < 0) {
                        scope.index = scope.images.length - 1;
                    }
                    showImage(scope.index);
                };
```

[https://github.com/SchwarzwaldFalke/ngGallery/blob/master/src/js/ngGallery.js](https://github.com/SchwarzwaldFalke/ngGallery/blob/master/src/js/ngGallery.js)

**Comment by thatisuday** [comment]
@SchwarzwaldFalke Sorry, I grabbed js file from your preview website `http://demo.jankuri.com/ngGallery`

There I thinks is the old version.
