### ISSUE TITLE
I don't know what's wrong here. 

### ISSUE THREAD

**Issue by SamuraiJack1337** [SchwarzwaldFalke/ngGallery#7]
http://stackoverflow.com/questions/33556430/nothing-shows-up-after-no-error-implementation-of-jankuri-ng-gallery

Have a look at that link.
I even tried replicating the exact same thing that you have done, as in formatting controllers in similar manner and even fed static  entries to self.images but still nothing shows up.

I don't know what's wrong here.

**Comment by SamuraiJack1337** [comment]
Hey man I sorted it out but there is another problem, I cannot see arrows for previous and next. 
Please direct me how can I add a new button to maybe call a function with argument that holds name of the photo. To remove photo.

**Comment by jkuri** [comment]
Hey, did you included fontawesome library?

**Comment by SamuraiJack1337** [comment]
No, I missed it. Thanks.
