### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by onyx1337** [SchwarzwaldFalke/ngGallery#8]
It seems that passing template into  _template-url_ attr in directive doesn't work.
Because attrs.templateUrl  in templateUrl method get just name instead of value of variable .

P.S.: Thank you for your gallery. It's great.

**Comment by JamieSellars** [comment]
this worked for me. 

Change the html attribute to templateurl="Path/to/template". 

In the directive templateurl method change the attrs property to
attrs.templateurl

**Comment by GiTweeker** [comment]
Is there any way to open a single image, from a controller using the directive .. 
I am using the gallery and also have an anchor tag on img tag display the image on a time.. I would like to use the plugin to open the image on the time line when clicked.. Any help would be nice

**Comment by jkuri** [comment]
Not sure I understand what you mean, but giving only one image in directive would solve this?

**Comment by GiTweeker** [comment]
![test](https://cloud.githubusercontent.com/assets/12827225/12371714/5c865212-bc3d-11e5-8aa5-67694fbc43dd.PNG)
Sorry about not being clear.. 
The image shows what I intend doing. A simple image viewer . I have already installed your plugin on a gallery section . I dont want to use another solution for the image viewer. 
Any Ideas?

**Comment by GiTweeker** [comment]
I was thinking maybe an attribute on the anchor tag  to pass the image, which can then open the gallery on click.

**Comment by jkuri** [comment]
You cannot use this directive like this, sorry.
